# Generated by Django 4.1.4 on 2024-03-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='startdate',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='companydescription',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='blog',
            name='companyname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='jobdescription',
            field=models.CharField(blank=True, max_length=5550),
        ),
        migrations.AddField(
            model_name='blog',
            name='worklocation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
