# Generated by Django 4.1.4 on 2024-03-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_date_blog_startdate_remove_blog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='companydescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='jobdescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
