# Generated by Django 4.1.4 on 2024-03-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_companydescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
