# Generated by Django 4.1.4 on 2024-03-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
