# Generated by Django 4.1.4 on 2024-03-29 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='title',
            new_name='degree',
        ),
    ]
