# Generated by Django 4.1.4 on 2024-03-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0009_auto_20210908_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='companyname',
            new_name='backend',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='companydescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='worklocation',
            new_name='frontend',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='jobdescription',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='startdate',
        ),
    ]
